### ISSUE TITLE
error message while editing html file

### ISSUE THREAD

**Issue by enricoreich** [rosieks/Rosieks.VisualStudio.Angular#2]
Hello,
if I try to edit an html file in VS2017 Community, an error message appears.

error from Activity.log:
```
System.ComponentModel.Composition.CompositionContractMismatchException:
	Cannot cast the underlying exported value of type 'Microsoft.Html.Editor.Completion.Def.IHtmlCompletionListProvider' to type 'Microsoft.Html.Editor.Completion.Def.IHtmlCompletionListProvider'.
		at System.ComponentModel.Composition.ExportServices.CastExportedValue[T](ICompositionElement element, Object exportedValue)
		at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
		at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1()
		at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue() at System.Lazy`1.get_Value()
		at Microsoft.Html.Editor.Completion.Engine.HtmlCompletionEngine.GetElementCompletionProviders(String completionType, String elementPrefix, String elementName)
		at Microsoft.Html.Editor.Completion.Engine.HtmlCompletionEngine.GetCompletionForAttributes(ElementNode element, String& completionType)
		at Microsoft.Html.Editor.Completion.Engine.HtmlCompletionEngine.GetAttributeNameCompletions(RootNode rootNode, Int32 position, ElementNode element, AttributeNode attribute, ITextRange& range, String& completionType)
		at Microsoft.Html.Editor.Completion.Engine.HtmlCompletionEngine.GetCompletionForLocation(RootNode rootNode, IContentType contentType, Int32 position, ElementNode& element, AttributeNode& attribute, ITextRange& range, String& completionType, Boolean autoShownCompletion)
		at Microsoft.Html.Editor.Completion.HtmlCompletionSource.PopulateCompletionList(Int32 position, ICompletionSession session, IList`1 completionSets) at Microsoft.Html.Editor.Completion.HtmlCompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets)
		at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()
		at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.TriggerCompletion(ITextView textView)
		at Microsoft.Web.Editor.Completion.CompletionController.TriggerCompletion()
		at Microsoft.Web.Editor.Completion.CompletionController.ShowCompletion(Boolean autoShownCompletion)
		at Microsoft.Web.Editor.Completion.CompletionController.OnPostTypeChar(Char typedCharacter)
		at Microsoft.Html.Editor.Completion.HtmlCompletionController.OnPostTypeChar(Char typedCharacter)
		at Microsoft.Web.Editor.Completion.TypingCommandHandler.OnPostTypeChar(Char typedChar)
		at Microsoft.Web.Editor.Completion.TypingCommandHandler.PostProcessInvoke(CommandResult result, Guid group, Int32 id, Object inputArg, Object& outputArg)
		at Microsoft.Html.Editor.Commands.HtmlTypingCommandHandler.PostProcessInvoke(CommandResult result, Guid group, Int32 id, Object inputArg, Object& outputArg)
		at Microsoft.Web.Editor.Controller.Controller.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg)
		at Microsoft.Web.Editor.Controller.ViewController.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg)
		at Microsoft.Html.Editor.Commands.HtmlMainController.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg)
		at Microsoft.VisualStudio.Html.Interop.CommandTargetToOleShim.Exec(Guid& guidCommandGroup, UInt32 commandID, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)
		at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
		at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
		at Rosieks.VisualStudio.Angular.Commands.CommandTargetBase`1.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
		
		in D:\projects\Rosieks.VisualStudio.Angular\Rosieks.VisualStudio.Angular\Commands\CommandTargetBase.cs:line 56
			at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
			at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
			at Rosieks.VisualStudio.Angular.Commands.CommandTargetBase`1.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
			
			in D:\projects\Rosieks.VisualStudio.Angular\Rosieks.VisualStudio.Angular\Commands\CommandTargetBase.cs:line 56
				at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
				at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
				at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
				at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
				at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
				at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
				at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
				at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```
Using ASPNET core with Angular 4.0, the html file is a component template. It does not matter what you edit (tag parameter, text, tags ....) the error appears once at the 1st html file that was opened after VS is started. After this error, working on the html code is possible without any problem.

**Comment by wizarrc** [comment]
same problem here. I installed it to get intellisense support for an Angular 4 html template.

**Comment by AlexzundeR** [comment]
I have the same problem. VS2017 Angular2 Html file.

**Comment by rosieks** [comment]
It looks that HTML editor doesn't support creating extensions for various versions of Visual Studio. So I have removed support for VS2015. New VSIX is already uploaded to gallery.
